---
- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Install ssl-cert
  apt:
    name: ssl-cert
    state: latest

- name: Replace NGINX config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Check NGINX configs
  shell: "/usr/sbin/nginx -t"
  register: nginx_config_status

- name: NGINX test status
  debug:
    msg: "{{ nginx_config_status.stderr_lines }}"

- name: NGINX test status
  debug:
    msg: "{{ nginx_config_status.rc }}"

- name: Service NGINX restart and enable on boot
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: nginx_config_status.rc == 0

- name: add default-conf for nginx_vhost
  template:
    src: templates/default.j2
    dest: "/etc/nginx/sites-enabled/{{ nginx_install_default_domain }}.conf"
    owner: "{{ nginx_install_nginx_user }}"
    group: root
    mode: 0644
  notify:
  - nginx_restarted
