- hosts: all
  become: true
  roles:
    - kerio-letsencrypt

  vars:
    lets_letsencrypt_email: "info@aits.life"
    lets_deploy_vhosts:
      # - server_name: domain1.aits.life
      #   state: present

      - server_name: domain2.aits.life
        state: absent

    # lets_dry_run: "--dry-run"
    lets_dry_run: ""
    lets_crontab_enable: "disable"
